version: '3.5'
services:

  mysql_1:
    image: mysql:8.0.3
    env_file: .env
    ports:
      - 3307:3306
    volumes:
      - mysql-1-data:/var/lib/mysql
      - ./etc/mysql/conf.d:/etc/mysql/conf.d:ro

  mysql_2:
    image: mysql:8.0.3
    env_file: .env
    ports:
      - "3308:3306"
    volumes:
      - mysql-2-data:/var/lib/mysql
      - ./etc/mysql2/conf.d/:/etc/mysql/conf.d:ro

volumes:
  mysql-1-data:
  mysql-2-data:
