version: '3.3'
services:

  mysql_master:
    image: mysql:8.0.3
    env_file: .env
    ports:
      - 33061:3306
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/master.sh:/docker-entrypoint-initdb.d/1-master-init.sh
    command:
      - --log-bin=mysql-bin
      - --server-id=1

  mysql_node:
    image: mysql:8.0.3
    env_file: .env
    ports:
      - "33062:3306"
    volumes:
      - mysql-node-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/node.sh:/docker-entrypoint-initdb.d/1-node-init.sh
    command:
      - --server-id=10
      - --character-set-server=utf8mb4

volumes:
  mysql-master-data:
  mysql-node-data:
